#!/usr/bin/env bash
set -euo pipefail

# Tynn Demo Mode Storage
# Manages local .tynn/ JSON files and TYNN.md markdown sync
#
# Usage:
#   storage.sh init              - Initialize demo mode storage
#   storage.sh add-task "title"  - Add a task
#   storage.sh add-wish "title" "type" "description"  - Add a wish
#   storage.sh list-tasks        - List all tasks as JSON
#   storage.sh list-wishes       - List all wishes as JSON
#   storage.sh update-task ID STATUS  - Update task status
#   storage.sh sync-markdown     - Regenerate TYNN.md from JSON
#   storage.sh export            - Export data for migration

TYNN_DIR=".tynn"
TASKS_FILE="$TYNN_DIR/tasks.json"
WISHES_FILE="$TYNN_DIR/wishes.json"
MARKDOWN_FILE="TYNN.md"

# Generate a simple local ID
generate_id() {
    echo "local-$(date +%s)-$RANDOM"
}

# Get current timestamp
timestamp() {
    date -u +"%Y-%m-%dT%H:%M:%SZ"
}

# Initialize storage
init() {
    mkdir -p "$TYNN_DIR"

    if [[ ! -f "$TASKS_FILE" ]]; then
        echo '{"tasks":[]}' > "$TASKS_FILE"
    fi

    if [[ ! -f "$WISHES_FILE" ]]; then
        echo '{"wishes":[]}' > "$WISHES_FILE"
    fi

    sync_markdown
    echo "✅ Demo mode initialized"
}

# Add a task
add_task() {
    local title="$1"
    local description="${2:-}"
    local id=$(generate_id)
    local ts=$(timestamp)

    local task=$(cat <<EOF
{
    "id": "$id",
    "title": "$title",
    "description": "$description",
    "status": "backlog",
    "created_at": "$ts",
    "updated_at": "$ts"
}
EOF
)

    # Add to tasks array
    local tasks=$(cat "$TASKS_FILE")
    echo "$tasks" | jq --argjson task "$task" '.tasks += [$task]' > "$TASKS_FILE"

    sync_markdown
    echo "$id"
}

# Add a wish
add_wish() {
    local title="$1"
    local type="$2"
    local description="$3"
    local id=$(generate_id)
    local ts=$(timestamp)

    local wish=$(cat <<EOF
{
    "id": "$id",
    "title": "$title",
    "type": "$type",
    "description": "$description",
    "created_at": "$ts"
}
EOF
)

    # Add to wishes array
    local wishes=$(cat "$WISHES_FILE")
    echo "$wishes" | jq --argjson wish "$wish" '.wishes += [$wish]' > "$WISHES_FILE"

    sync_markdown
    echo "$id"
}

# List tasks
list_tasks() {
    cat "$TASKS_FILE"
}

# List wishes
list_wishes() {
    cat "$WISHES_FILE"
}

# Update task status
update_task() {
    local id="$1"
    local status="$2"
    local ts=$(timestamp)

    local tasks=$(cat "$TASKS_FILE")
    echo "$tasks" | jq --arg id "$id" --arg status "$status" --arg ts "$ts" \
        '(.tasks[] | select(.id == $id)) |= (.status = $status | .updated_at = $ts)' \
        > "$TASKS_FILE"

    sync_markdown
    echo "✅ Task $id updated to $status"
}

# Sync JSON to markdown
sync_markdown() {
    local tasks=$(cat "$TASKS_FILE" 2>/dev/null || echo '{"tasks":[]}')
    local wishes=$(cat "$WISHES_FILE" 2>/dev/null || echo '{"wishes":[]}')

    cat > "$MARKDOWN_FILE" <<EOF
# Tynn (Demo Mode)

Local project tracking. Run \`/tynn sync\` to migrate to Tynn.

---

## Tasks

### Doing
EOF

    echo "$tasks" | jq -r '.tasks[] | select(.status == "doing") | "- [ ] **\(.title)**\(if .description != "" then " — \(.description)" else "" end)"' >> "$MARKDOWN_FILE"

    cat >> "$MARKDOWN_FILE" <<EOF

### QA
EOF

    echo "$tasks" | jq -r '.tasks[] | select(.status == "qa") | "- [ ] **\(.title)**\(if .description != "" then " — \(.description)" else "" end)"' >> "$MARKDOWN_FILE"

    cat >> "$MARKDOWN_FILE" <<EOF

### Backlog
EOF

    echo "$tasks" | jq -r '.tasks[] | select(.status == "backlog") | "- [ ] \(.title)\(if .description != "" then " — \(.description)" else "" end)"' >> "$MARKDOWN_FILE"

    cat >> "$MARKDOWN_FILE" <<EOF

### Done
EOF

    echo "$tasks" | jq -r '.tasks[] | select(.status == "done") | "- [x] ~~\(.title)~~"' >> "$MARKDOWN_FILE"

    cat >> "$MARKDOWN_FILE" <<EOF

---

## Wishes

EOF

    echo "$wishes" | jq -r '.wishes[] | "- **\(.type | ascii_upcase)**: \(.title) — \(.description)"' >> "$MARKDOWN_FILE"

    cat >> "$MARKDOWN_FILE" <<EOF

---

*Generated by Tynn Demo Mode*
EOF
}

# Export for migration
export_data() {
    cat <<EOF
{
    "tasks": $(cat "$TASKS_FILE" | jq '.tasks'),
    "wishes": $(cat "$WISHES_FILE" | jq '.wishes'),
    "exported_at": "$(timestamp)"
}
EOF
}

# Check if demo mode is active
is_active() {
    [[ -d "$TYNN_DIR" ]] && echo "true" || echo "false"
}

# Main command dispatcher
case "${1:-}" in
    init)
        init
        ;;
    add-task)
        add_task "${2:-Untitled}" "${3:-}"
        ;;
    add-wish)
        add_wish "${2:-Untitled}" "${3:-enhancement}" "${4:-}"
        ;;
    list-tasks)
        list_tasks
        ;;
    list-wishes)
        list_wishes
        ;;
    update-task)
        update_task "$2" "$3"
        ;;
    sync-markdown)
        sync_markdown
        ;;
    export)
        export_data
        ;;
    is-active)
        is_active
        ;;
    *)
        echo "Usage: storage.sh {init|add-task|add-wish|list-tasks|list-wishes|update-task|sync-markdown|export|is-active}"
        exit 1
        ;;
esac
